apiVersion: v1
kind: Pod
metadata:
  name: is-ryan-working-backend
  labels:
    name: is-ryan-working-backend
spec:
  containers:
  - name: is-ryan-working-backend
    image: ryanmjacobs/is-ryan-working-backend:1.00
    ports:
    - containerPort: 2000
    env:
      - name:  KEY
        value: ajsnav

apiVersion: v1
kind: Service
metadata:
  name: is-ryan-working-backend
spec:
  selector:
    app: is-ryan-working-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2000
