apiVersion: v1
kind: Pod
metadata:
  name: getset
  labels:
    name: getset
spec:
  containers:
  - name: getset
    image: ryanmjacobs/getset:0.01
    ports:
    - containerPort: 2000
    env:
      - name:  KEY
        value: ajsnav

apiVersion: v1
kind: Service
metadata:
  name: getset
spec:
  selector:
    app: getset
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2000
